services:

  user-service:
    build:
      context: ..
      dockerfile: user-service/Dockerfile
      args:
        JAR_FILE: user-service/build/libs/*.jar

    env_file:
      - ../.env

    container_name: user-service

    ports:
      - "9000:9000"

    networks:
      - delivery-network


  # Hub Service
  hub-service:
    build:
      context: ..
      dockerfile: hub-service/Dockerfile
      args:
        JAR_FILE: hub-service/build/libs/*.jar

    env_file:
      - ../.env

    container_name: hub-service

    ports:
      - "9005:9005"

    networks:
      - delivery-network



networks:
  delivery-network:
    external: true