spring:
  application:
    name: eureka-server


server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans