server:
  port: 9001

spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:delivery_db}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: delivery_schema
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: delivery_schema
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

system:
  id: ${SYSTEM_ID}

jwt:
  secret: ${JWT_SECRET:local-dev-only-secret-key-please-override-in-env-file-32bytes-min}